name: Test

on:
  push:
  pull_request:
    branches: [develop, test]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test job
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.4

      - name: Create test file
        run: echo "asdfasdfasdf" > test.txt

      - name: SharePoint uploader
        uses: su-dont/share-point-uploader@v2.0
        with:
          sp_url: https://verimatrix.sharepoint.com/:f:/r/sites/productdocumentation
          sp_username: ${{ secrets.SP_USERNAME }}
          sp_password: ${{ secrets.SP_PASSWORD }}
          sp_folder: /Shared Documents/Watermarking/Standalone Android SDK
          sp_file_name: my_file.txt
          file: test.txt
